### ISSUE TITLE
直接配置下   运行npm run serve出现错误

### ISSUE THREAD

**Issue by daxianghrh** [ZhangMingZhao1/StreamerHelper#164]
hrh@hrh-ubuntu:~/StreamerHelper$ npm run serve 

> streamer_helper@1.0.0 serve /home/hrh/StreamerHelper
> npm run build && pm2 start ./dist/index.js

> streamer_helper@1.0.0 build /home/hrh/StreamerHelper
> tsc --project tsconfig.json && tsc-alias -p tsconfig.json

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at m (/home/hrh/StreamerHelper/node_modules/mylas/build/index.js:1:852)
    at /home/hrh/StreamerHelper/node_modules/mylas/build/index.js:1:35
    at O (/home/hrh/StreamerHelper/node_modules/mylas/build/index.js:1:1366)
    at /home/hrh/StreamerHelper/node_modules/mylas/build/index.js:1:35
    at Object.<anonymous> (/home/hrh/StreamerHelper/node_modules/mylas/build/index.js:3:6056)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streamer_helper@1.0.0 build: `tsc --project tsconfig.json && tsc-alias -p tsconfig.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streamer_helper@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hrh/.npm/_logs/2022-08-08T03_03_08_091Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streamer_helper@1.0.0 serve: `npm run build && pm2 start ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streamer_helper@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hrh/.npm/_logs/2022-08-08T03_03_08_098Z-debug.log

**Comment by umuoy1** [comment]
检查nodejs版本
