### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by yesmiley** [ZhangMingZhao1/StreamerHelper#33]
```
[root@VM-8-12-centos StreamerHelper]# npm run serve

> streamer_helper@1.0.0 serve /root/StreamerHelper
> npm run build && pm2 start ./dist/app.js


> streamer_helper@1.0.0 build /root/StreamerHelper
> tsc

/usr/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/constants.js:10:14)

npm ERR! Linux 3.10.0-1127.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! streamer_helper@1.0.0 serve: `npm run build && pm2 start ./dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streamer_helper@1.0.0 serve script 'npm run build && pm2 start ./dist/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the streamer_helper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && pm2 start ./dist/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs streamer_helper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls streamer_helper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/StreamerHelper/npm-debug.log
```

**Comment by ZhangMingZhao1** [comment]
"node v6.17.1 " node版本太低了，升级到最新的稳定版本吧
